import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getServerSession } from "next-auth";
import AuthProvider from "@/utils/session_Provider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Merry Match",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <AuthProvider session={session}>
      <html lang="en">
        <body className={nunito.className}>
          <div>{children}</div>
          <ToastContainer position="top-center" />
        </body>
      </html>
    </AuthProvider>
  );
}
